twig:
    file_name_pattern: '*.twig'
    paths:
        '%kernel.project_dir%/templates': ~
        '%kernel.project_dir%/templates/login': security

when@test:
    twig:
        strict_variables: true
